AWSTemplateFormatVersion: '2010-09-09'
Description: Bedrock setup for Reporting Agent

Resources:
  BedrockAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BedrockAccess
      Roles:
        - !Ref ReportingAgentRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"
