AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Buckets for templates and generated reports

Resources:
  TemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: genieai-report-templates
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: genieai-generated-reports
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
